/**
 * Expo config plugin: patch fmt/base.h to disable consteval.
 *
 * Problem: fmt 11.x's base.h has an #if chain that unconditionally sets
 * FMT_USE_CONSTEVAL=1 when __cpp_consteval is defined (Xcode 16+).
 * Xcode 16's Clang advertises consteval support but rejects certain
 * consteval template patterns used by fmt, causing build failures.
 *
 * Fix: Insert #define FMT_USE_CONSTEVAL 0 after the include guard, then
 * wrap the detection #if chain with #ifndef FMT_USE_CONSTEVAL so our
 * pre-definition takes precedence.
 */
const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

module.exports = function withFmtFix(config) {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const iosDir = config.modRequest.platformProjectRoot;
      const scriptPath = path.join(iosDir, "patch-fmt.sh");

      // Write the patch script that runs after pod install
      const script = `#!/bin/bash
# Auto-generated by withFmtFix.js
# Patches fmt/base.h to disable consteval for Xcode 16+ compatibility
set -e

PODS_DIR="${iosDir}/Pods"
if [ ! -d "$PODS_DIR" ]; then
  echo "[withFmtFix] No Pods directory found, skipping."
  exit 0
fi

BASEFILE="$PODS_DIR/fmt/include/fmt/base.h"
if [ ! -f "$BASEFILE" ]; then
  echo "[withFmtFix] fmt/base.h not found, skipping."
  exit 0
fi

if grep -q "withFmtFix" "$BASEFILE"; then
  echo "[withFmtFix] Already patched, skipping."
  exit 0
fi

chmod u+w "$BASEFILE"

python3 -c "
with open('$BASEFILE', 'r') as f:
    c = f.read()

# 1) Insert #define FMT_USE_CONSTEVAL 0 after include guard
c = c.replace(
    '#define FMT_BASE_H_',
    '#define FMT_BASE_H_\\n// [withFmtFix] Force disable consteval for Xcode 16+\\n#define FMT_USE_CONSTEVAL 0',
    1
)

# 2) Wrap detection block with #ifndef
c = c.replace(
    '// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.',
    '// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\\n#ifndef FMT_USE_CONSTEVAL',
    1
)

# 3) Close #ifndef before #if FMT_USE_CONSTEVAL
old = '''#else
#  define FMT_USE_CONSTEVAL 0
#endif
#if FMT_USE_CONSTEVAL'''
new = '''#else
#  define FMT_USE_CONSTEVAL 0
#endif
#endif  // ifndef FMT_USE_CONSTEVAL
#if FMT_USE_CONSTEVAL'''
c = c.replace(old, new, 1)

with open('$BASEFILE', 'w') as f:
    f.write(c)
"

echo "[withFmtFix] Patched fmt/base.h successfully."
`;

      fs.writeFileSync(scriptPath, script, { mode: 0o755 });

      // Modify Podfile to run patch after pod install
      const podfilePath = path.join(iosDir, "Podfile");
      if (fs.existsSync(podfilePath)) {
        let podfile = fs.readFileSync(podfilePath, "utf8");
        if (!podfile.includes("patch-fmt.sh")) {
          podfile = podfile.replace(
            /(react_native_post_install\([\s\S]*?:ccache_enabled\s*=>.*?\n\s*\))/m,
            `$1\n\n    # Patch fmt headers for Xcode 16+ consteval fix\n    system("bash", "${scriptPath}")`
          );
          fs.writeFileSync(podfilePath, podfile);
        }
      }

      return config;
    },
  ]);
};
