#!/bin/bash
# Auto-generated by withFmtFix.js
# Patches fmt/base.h to disable consteval for Xcode 16+ compatibility
set -e

PODS_DIR="/Users/sunjinlee/workspace/wod-strategist/ios/Pods"
if [ ! -d "$PODS_DIR" ]; then
  echo "[withFmtFix] No Pods directory found, skipping."
  exit 0
fi

BASEFILE="$PODS_DIR/fmt/include/fmt/base.h"
if [ ! -f "$BASEFILE" ]; then
  echo "[withFmtFix] fmt/base.h not found, skipping."
  exit 0
fi

if grep -q "withFmtFix" "$BASEFILE"; then
  echo "[withFmtFix] Already patched, skipping."
  exit 0
fi

chmod u+w "$BASEFILE"

python3 -c "
with open('$BASEFILE', 'r') as f:
    c = f.read()

# 1) Insert #define FMT_USE_CONSTEVAL 0 after include guard
c = c.replace(
    '#define FMT_BASE_H_',
    '#define FMT_BASE_H_\n// [withFmtFix] Force disable consteval for Xcode 16+\n#define FMT_USE_CONSTEVAL 0',
    1
)

# 2) Wrap detection block with #ifndef
c = c.replace(
    '// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.',
    '// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\n#ifndef FMT_USE_CONSTEVAL',
    1
)

# 3) Close #ifndef before #if FMT_USE_CONSTEVAL
old = '''#else
#  define FMT_USE_CONSTEVAL 0
#endif
#if FMT_USE_CONSTEVAL'''
new = '''#else
#  define FMT_USE_CONSTEVAL 0
#endif
#endif  // ifndef FMT_USE_CONSTEVAL
#if FMT_USE_CONSTEVAL'''
c = c.replace(old, new, 1)

with open('$BASEFILE', 'w') as f:
    f.write(c)
"

echo "[withFmtFix] Patched fmt/base.h successfully."
