package worker

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/hibiken/asynq"
	"github.com/wod-strategist/api/internal/db"
	"github.com/wod-strategist/api/internal/subtitle"
	"go.uber.org/zap"
)

// defaultTTSVoice is the prebuilt voice used for TTS narration.
// Change this to any of the 30 supported voices (e.g. "Aoede", "Charon", "Puck").
// Korean is auto-detected by the model.
const defaultTTSVoice = "Laomedeia"

// ttsToneDirectives maps fitness levels to Gemini TTS audio tags that control
// the delivery tone of the coaching narration.
//
// Gemini TTS supports inline tags like [soft], [loud], [aggressive] to steer
// voice performance. See: https://ai.google.dev/gemini-api/docs/text-generation#tts
var ttsToneDirectives = map[string]string{
	"beginner":     "[soft, kind, encouraging, warm] ",
	"intermediate": "[loud, energetic, assertive, intense] ",
	"advanced":     "[very aggressive, commanding, intense, shouting] ",
}

// HardSubPayload is the payload for the hardsub:generate task.
type HardSubPayload struct {
	SessionID string `json:"session_id"`
	ProfileID uint   `json:"profile_id"`
}

// NewGenerateHardSubTask creates a new hardsub generation task.
func NewGenerateHardSubTask(sessionID string, profileID uint) (*asynq.Task, error) {
	payload := HardSubPayload{
		SessionID: sessionID,
		ProfileID: profileID,
	}
	data, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	return asynq.NewTask(TypeGenerateHardSub, data), nil
}

// HandleGenerateHardSubTask downloads merged.mp4 from GCS and burns subtitles
// into it, producing hardsubbed.mp4.
//
// Subtitles are generated by mixing two sources:
//   - Final analysis (✅ strengths / ⚠️ weaknesses) for segments that were analysed
//   - Real-time chunk cues for time gaps not covered by the final analysis
//
// TTS narration is generated only for chunk (realtime) feedback entries using
// gemini-3.1-flash-tts-preview. Final analysis entries remain subtitle-only
// to keep the detailed coaching text readable without audio clutter.
//
// If the final analysis is not yet available (e.g. manual trigger before
// analysis completes), falls back to chunk-only subtitles.
func (w *Worker) HandleGenerateHardSubTask(ctx context.Context, t *asynq.Task) error {
	var p HardSubPayload
	if err := json.Unmarshal(t.Payload(), &p); err != nil {
		return fmt.Errorf("json.Unmarshal failed: %v: %w", err, asynq.SkipRetry)
	}

	if err := validateSessionID(p.SessionID); err != nil {
		w.logger.Error("Invalid session ID for hardsub", zap.String("session_id", p.SessionID))
		return err
	}

	w.logger.Info("Processing hardsub generation",
		zap.String("session_id", p.SessionID),
		zap.Uint("profile_id", p.ProfileID))

	// 1. Fetch the final analysis result from DB (may be absent).
	var analysisOutput string
	var result db.AnalysisResult
	if err := w.DB.Where("session_id = ? AND status = ? AND analysis_type = ?",
		p.SessionID, "COMPLETED", db.AnalysisTypeWOD).
		Order("created_at DESC").
		First(&result).Error; err != nil {
		w.logger.Warn("No completed analysis found, will use chunk-only subtitles",
			zap.String("session_id", p.SessionID),
			zap.Error(err))
	} else {
		analysisOutput = result.Output
	}

	// 2. Fetch chunk analysis results (real-time per-10s feedback).
	var chunks []db.ChunkAnalysisResult
	if err := w.DB.Where("session_id = ? AND status = ?", p.SessionID, "COMPLETED").
		Order("start_secs ASC").
		Find(&chunks).Error; err != nil {
		w.logger.Warn("Failed to query chunk analysis",
			zap.String("session_id", p.SessionID),
			zap.Error(err))
	}

	// 3. Generate mixed SRT: final analysis (✅/⚠️) for analyzed segments,
	//    chunk cues fill time gaps where no final analysis exists.
	srt := subtitle.FormatMixedSRT(analysisOutput, chunks)
	if srt == "" {
		w.logger.Info("No subtitle content from either source, skipping hardsub",
			zap.String("session_id", p.SessionID))
		return fmt.Errorf("no subtitle content: %w", asynq.SkipRetry)
	}

	w.logger.Info("Generated mixed SRT",
		zap.String("session_id", p.SessionID),
		zap.Bool("has_final_analysis", analysisOutput != ""),
		zap.Int("chunk_count", len(chunks)),
		zap.Int("srt_length", len(srt)))

	// 4. Create temp directory
	tmpDir, err := createTempDir("hardsub")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	// 5. Download merged.mp4 from GCS
	mergedGCSURI := fmt.Sprintf("gs://%s/videos/%d/%s/merged.mp4", w.BucketName, p.ProfileID, p.SessionID)
	mergedPath := filepath.Join(tmpDir, "merged.mp4")

	if err := w.StorageClient.DownloadFile(ctx, mergedGCSURI, mergedPath); err != nil {
		w.logger.Error("Failed to download merged.mp4 for hardsub",
			zap.String("session_id", p.SessionID),
			zap.String("gcs_uri", mergedGCSURI),
			zap.Error(err))
		return fmt.Errorf("download merged.mp4: %w", err)
	}

	// 6. Write SRT and burn subtitles via FFmpeg.
	srtPath := filepath.Join(tmpDir, "feedback.srt")
	if err := os.WriteFile(srtPath, []byte(srt), 0o644); err != nil {
		return fmt.Errorf("failed to write SRT: %w", err)
	}

	hardSubPath := filepath.Join(tmpDir, fmt.Sprintf("hardsubbed_%s.mp4", p.SessionID))

	w.logger.Info("Burning mixed subtitles into video",
		zap.String("session_id", p.SessionID),
		zap.String("input", mergedPath),
		zap.String("srt", srtPath),
		zap.String("output", hardSubPath))

	if err := runFFmpegHardSub(ctx, w.logger, mergedPath, srtPath, hardSubPath); err != nil {
		w.logger.Error("Hardsub FFmpeg failed",
			zap.String("session_id", p.SessionID),
			zap.Error(err))
		return fmt.Errorf("hardsub ffmpeg: %w", err)
	}

	// 7. Generate TTS narration for chunk (realtime) feedback entries.
	//    This is best-effort: if TTS fails, we still upload the subtitle-only video.
	//
	//    NOTE (cost): Each chunk triggers a separate TTS API call.
	//    A 5-min workout ≈ 30 chunks ≈ 30 calls. gemini-3.1-flash-tts-preview
	//    is priced per character; chunk feedback is typically ~100 chars each.
	fitnessLevel := w.lookupFitnessLevel(p.ProfileID)
	narrationPath := filepath.Join(tmpDir, "narration.wav")
	hasNarration := w.generateChunkNarration(ctx, p.SessionID, p.ProfileID, chunks, fitnessLevel, tmpDir, narrationPath)

	uploadPath := hardSubPath
	if hasNarration {
		// 7.5. Mix narration audio track into the hardsubbed video.
		//      Uses -c:v copy to avoid re-encoding video — only audio is processed.
		mixedPath := filepath.Join(tmpDir, fmt.Sprintf("mixed_%s.mp4", p.SessionID))
		if err := runFFmpegMixAudio(ctx, w.logger, hardSubPath, narrationPath, mixedPath); err != nil {
			w.logger.Warn("Audio mixing failed, uploading subtitle-only video",
				zap.String("session_id", p.SessionID),
				zap.Error(err))
			// Fall through — uploadPath stays as hardSubPath
		} else {
			uploadPath = mixedPath
			// Free the intermediate hardsub file from tmpfs
			_ = os.Remove(hardSubPath)
		}
	}

	// 8. Upload hardsubbed.mp4 to GCS.
	hardSubObjectName := fmt.Sprintf("videos/%d/%s/hardsubbed.mp4", p.ProfileID, p.SessionID)
	hardSubGCSURI, err := w.StorageClient.UploadFromFile(ctx, uploadPath, hardSubObjectName)
	if err != nil {
		return fmt.Errorf("failed to upload hardsubbed video: %w", err)
	}

	w.logger.Info("Hardsub generation completed",
		zap.String("session_id", p.SessionID),
		zap.String("gcs_uri", hardSubGCSURI),
		zap.Bool("has_tts_narration", hasNarration))

	return nil
}

// ttsClip represents a single TTS audio clip positioned at a video timestamp.
type ttsClip struct {
	path     string
	startSec float64
}

// ttsCleanupRegex strips subtitle formatting artifacts that shouldn't be spoken:
// - [강점], [개선] section markers
// - [NNN bpm] heart rate badges
var ttsCleanupRegex = regexp.MustCompile(`\[(강점|개선|\d+\s*bpm)\]\s*`)

// generateChunkNarration generates TTS audio for each chunk's coaching feedback
// and combines them into a single narration WAV file aligned to video timestamps.
//
// fitnessLevel controls the TTS delivery tone (beginner=soft, intermediate=loud,
// advanced=aggressive). See ttsToneDirectives.
//
// Returns true if narration was successfully generated, false otherwise.
func (w *Worker) generateChunkNarration(ctx context.Context, sessionID string, profileID uint, chunks []db.ChunkAnalysisResult, fitnessLevel, tmpDir, outputPath string) bool {
	if w.GeminiClient == nil {
		return false
	}

	tonePrefix := ttsToneDirectives[fitnessLevel] // empty string if unknown level

	w.logger.Info("Generating TTS narration",
		zap.String("fitness_level", fitnessLevel),
		zap.String("tone_prefix", tonePrefix))

	var clips []ttsClip
	for i, ch := range chunks {
		if ch.Status != "COMPLETED" || ch.StartSecs == nil || ch.EndSecs == nil {
			continue
		}
		text := strings.TrimSpace(ch.Output)
		if text == "" {
			continue
		}

		// Clean up subtitle-specific markers for natural speech
		text = ttsCleanupRegex.ReplaceAllString(text, "")
		text = strings.TrimSpace(text)
		if text == "" {
			continue
		}

		// Prepend tone directive so TTS delivers with the right energy for this level
		ttsText := tonePrefix + text

		wavPath := filepath.Join(tmpDir, fmt.Sprintf("tts_%03d.wav", i))
		usage, err := w.GeminiClient.GenerateSpeech(ctx, ttsText, defaultTTSVoice, wavPath)
		if err != nil {
			w.logger.Warn("TTS generation failed for chunk, skipping",
				zap.Int("chunk_index", i),
				zap.Float64("start_secs", *ch.StartSecs),
				zap.Error(err))
			continue
		}
		w.saveTokenUsage(sessionID, profileID, "hardsub:tts", usage)

		clips = append(clips, ttsClip{path: wavPath, startSec: *ch.StartSecs})
	}

	if len(clips) == 0 {
		w.logger.Info("No TTS clips generated, skipping narration")
		return false
	}

	w.logger.Info("TTS clips generated",
		zap.Int("clip_count", len(clips)),
		zap.Int("chunk_count", len(chunks)))

	// Build narration track: overlay all clips at their respective time offsets
	// using FFmpeg's adelay filter to position each clip correctly.
	if err := buildNarrationTrack(ctx, w.logger, clips, outputPath); err != nil {
		w.logger.Warn("Failed to build narration track",
			zap.Error(err))
		return false
	}

	return true
}

// buildNarrationTrack combines multiple TTS WAV clips into a single audio track,
// positioning each clip at its video timestamp using FFmpeg's adelay + amix filters.
//
// The approach:
// 1. Each clip gets an adelay filter to shift it to the right time offset
// 2. All delayed clips are mixed together with amix
// 3. Output is a single WAV file aligned to video time
func buildNarrationTrack(ctx context.Context, log *zap.Logger, clips []ttsClip, outputPath string) error {
	if len(clips) == 0 {
		return fmt.Errorf("no clips to build narration from")
	}

	// For a single clip, just delay it
	if len(clips) == 1 {
		delayMs := int(clips[0].startSec * 1000)
		args := []string{
			"-i", clips[0].path,
			"-af", fmt.Sprintf("adelay=%d|%d,apad=pad_dur=0", delayMs, delayMs),
			"-y", outputPath,
		}
		return runFFmpegCmd(ctx, log, "narration-single", args)
	}

	// Multiple clips: build a complex filter graph
	var inputs []string
	var filterParts []string
	var mixInputLabels []string

	for i, clip := range clips {
		inputs = append(inputs, "-i", clip.path)
		delayMs := int(clip.startSec * 1000)
		label := fmt.Sprintf("[d%d]", i)
		filterParts = append(filterParts,
			fmt.Sprintf("[%d:a]adelay=%d|%d,apad=pad_dur=0%s", i, delayMs, delayMs, label))
		mixInputLabels = append(mixInputLabels, label)
	}

	// Mix all delayed clips together
	filterComplex := strings.Join(filterParts, ";") +
		";" + strings.Join(mixInputLabels, "") +
		fmt.Sprintf("amix=inputs=%d:duration=longest:normalize=0[out]", len(clips))

	args := append(inputs,
		"-filter_complex", filterComplex,
		"-map", "[out]",
		"-y", outputPath,
	)

	return runFFmpegCmd(ctx, log, "narration-mix", args)
}

// runFFmpegMixAudio mixes a narration audio track into a video's existing audio.
// Uses -c:v copy to avoid re-encoding video (only audio is re-encoded).
// Narration volume is reduced (0.6) so it doesn't overpower the original audio.
//
// If the video has no audio stream (e.g. the hardsub step dropped it, or the
// original recording was silent), the narration is added as the sole audio track.
func runFFmpegMixAudio(ctx context.Context, log *zap.Logger, videoPath, audioPath, outputPath string) error {
	// Probe whether the video already has an audio stream.
	hasAudio := videoHasAudioStream(ctx, videoPath)

	var args []string
	if hasAudio {
		// Mix original video audio [0:a] with narration [1:a]
		// Volume weights: original=1.0, narration=0.6
		args = []string{
			"-i", videoPath,
			"-i", audioPath,
			"-filter_complex", "[1:a]volume=0.6[narr];[0:a][narr]amix=inputs=2:duration=first:dropout_transition=2[aout]",
			"-map", "0:v",
			"-map", "[aout]",
			"-c:v", "copy",
			"-c:a", "aac", "-b:a", "128k",
			"-y", outputPath,
		}
	} else {
		// No existing audio — add narration as the sole audio track
		log.Info("Video has no audio stream, adding narration as sole audio track")
		args = []string{
			"-i", videoPath,
			"-i", audioPath,
			"-filter_complex", "[1:a]volume=0.8[aout]",
			"-map", "0:v",
			"-map", "[aout]",
			"-c:v", "copy",
			"-c:a", "aac", "-b:a", "128k",
			"-shortest",
			"-y", outputPath,
		}
	}

	return runFFmpegCmd(ctx, log, "mix-audio", args)
}

// videoHasAudioStream probes a video file to check if it contains an audio stream.
func videoHasAudioStream(ctx context.Context, videoPath string) bool {
	cmd := exec.CommandContext(ctx, "ffprobe",
		"-v", "error",
		"-select_streams", "a",
		"-show_entries", "stream=codec_type",
		"-of", "csv=p=0",
		videoPath,
	)
	output, err := cmd.Output()
	if err != nil {
		return false
	}
	return len(strings.TrimSpace(string(output))) > 0
}

// runFFmpegCmd is a generic FFmpeg runner with logging.
func runFFmpegCmd(ctx context.Context, log *zap.Logger, label string, args []string) error {
	log.Info("Running FFmpeg "+label, zap.Strings("args", args))

	cmd := exec.CommandContext(ctx, "ffmpeg", args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		log.Error("FFmpeg "+label+" failed", zap.Error(err), zap.String("output", string(output)))
		return fmt.Errorf("ffmpeg %s: %s: %w", label, string(output), err)
	}

	log.Info("FFmpeg " + label + " completed")
	return nil
}

// enqueueHardSub is a best-effort helper that enqueues a hardsub generation task.
// Errors are logged but never propagated — hardsub is a nice-to-have, not critical.
func (w *Worker) enqueueHardSub(sessionID string, profileID uint) {
	if profileID == 0 {
		return
	}

	task, err := NewGenerateHardSubTask(sessionID, profileID)
	if err != nil {
		w.logger.Warn("Failed to create hardsub task",
			zap.String("session_id", sessionID),
			zap.Error(err))
		return
	}

	if _, err := w.QueueClient.Enqueue(task); err != nil {
		w.logger.Warn("Failed to enqueue hardsub task",
			zap.String("session_id", sessionID),
			zap.Error(err))
		return
	}

	w.logger.Info("Hardsub generation auto-enqueued after analysis",
		zap.String("session_id", sessionID),
		zap.Uint("profile_id", profileID))
}
