package worker

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/hibiken/asynq"
	"github.com/wod-strategist/api/internal/db"
	"github.com/wod-strategist/api/internal/subtitle"
	"go.uber.org/zap"
)

// HardSubPayload is the payload for the hardsub:generate task.
type HardSubPayload struct {
	SessionID string `json:"session_id"`
	ProfileID uint   `json:"profile_id"`
}

// NewGenerateHardSubTask creates a new hardsub generation task.
func NewGenerateHardSubTask(sessionID string, profileID uint) (*asynq.Task, error) {
	payload := HardSubPayload{
		SessionID: sessionID,
		ProfileID: profileID,
	}
	data, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	return asynq.NewTask(TypeGenerateHardSub, data), nil
}

// HandleGenerateHardSubTask downloads merged.mp4 from GCS and burns subtitles
// into it, producing hardsubbed.mp4.
//
// Subtitles are generated by mixing two sources:
//   - Final analysis (✅ strengths / ⚠️ weaknesses) for segments that were analysed
//   - Real-time chunk cues for time gaps not covered by the final analysis
//
// If the final analysis is not yet available (e.g. manual trigger before
// analysis completes), falls back to chunk-only subtitles.
func (w *Worker) HandleGenerateHardSubTask(ctx context.Context, t *asynq.Task) error {
	var p HardSubPayload
	if err := json.Unmarshal(t.Payload(), &p); err != nil {
		return fmt.Errorf("json.Unmarshal failed: %v: %w", err, asynq.SkipRetry)
	}

	if err := validateSessionID(p.SessionID); err != nil {
		w.logger.Error("Invalid session ID for hardsub", zap.String("session_id", p.SessionID))
		return err
	}

	w.logger.Info("Processing hardsub generation",
		zap.String("session_id", p.SessionID),
		zap.Uint("profile_id", p.ProfileID))

	// 1. Fetch the final analysis result from DB (may be absent).
	var analysisOutput string
	var result db.AnalysisResult
	if err := w.DB.Where("session_id = ? AND status = ? AND analysis_type = ?",
		p.SessionID, "COMPLETED", db.AnalysisTypeWOD).
		Order("created_at DESC").
		First(&result).Error; err != nil {
		w.logger.Warn("No completed analysis found, will use chunk-only subtitles",
			zap.String("session_id", p.SessionID),
			zap.Error(err))
	} else {
		analysisOutput = result.Output
	}

	// 2. Fetch chunk analysis results (real-time per-10s feedback).
	var chunks []db.ChunkAnalysisResult
	if err := w.DB.Where("session_id = ? AND status = ?", p.SessionID, "COMPLETED").
		Order("start_secs ASC").
		Find(&chunks).Error; err != nil {
		w.logger.Warn("Failed to query chunk analysis",
			zap.String("session_id", p.SessionID),
			zap.Error(err))
	}

	// 3. Generate mixed SRT: final analysis (✅/⚠️) for analyzed segments,
	//    chunk cues fill time gaps where no final analysis exists.
	srt := subtitle.FormatMixedSRT(analysisOutput, chunks)
	if srt == "" {
		w.logger.Info("No subtitle content from either source, skipping hardsub",
			zap.String("session_id", p.SessionID))
		return fmt.Errorf("no subtitle content: %w", asynq.SkipRetry)
	}

	w.logger.Info("Generated mixed SRT",
		zap.String("session_id", p.SessionID),
		zap.Bool("has_final_analysis", analysisOutput != ""),
		zap.Int("chunk_count", len(chunks)),
		zap.Int("srt_length", len(srt)))

	// 3. Create temp directory
	tmpDir, err := createTempDir("hardsub")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	// 4. Download merged.mp4 from GCS
	mergedGCSURI := fmt.Sprintf("gs://%s/videos/%d/%s/merged.mp4", w.BucketName, p.ProfileID, p.SessionID)
	mergedPath := filepath.Join(tmpDir, "merged.mp4")

	if err := w.StorageClient.DownloadFile(ctx, mergedGCSURI, mergedPath); err != nil {
		w.logger.Error("Failed to download merged.mp4 for hardsub",
			zap.String("session_id", p.SessionID),
			zap.String("gcs_uri", mergedGCSURI),
			zap.Error(err))
		return fmt.Errorf("download merged.mp4: %w", err)
	}

	// 5. Write SRT and burn subtitles via FFmpeg.
	srtPath := filepath.Join(tmpDir, "feedback.srt")
	if err := os.WriteFile(srtPath, []byte(srt), 0o644); err != nil {
		return fmt.Errorf("failed to write SRT: %w", err)
	}

	hardSubPath := filepath.Join(tmpDir, fmt.Sprintf("hardsubbed_%s.mp4", p.SessionID))

	w.logger.Info("Burning mixed subtitles into video",
		zap.String("session_id", p.SessionID),
		zap.String("input", mergedPath),
		zap.String("srt", srtPath),
		zap.String("output", hardSubPath))

	if err := runFFmpegHardSub(ctx, w.logger, mergedPath, srtPath, hardSubPath); err != nil {
		w.logger.Error("Hardsub FFmpeg failed",
			zap.String("session_id", p.SessionID),
			zap.Error(err))
		return fmt.Errorf("hardsub ffmpeg: %w", err)
	}

	// 6. Upload hardsubbed.mp4 to GCS.
	hardSubObjectName := fmt.Sprintf("videos/%d/%s/hardsubbed.mp4", p.ProfileID, p.SessionID)
	hardSubGCSURI, err := w.StorageClient.UploadFromFile(ctx, hardSubPath, hardSubObjectName)
	if err != nil {
		return fmt.Errorf("failed to upload hardsubbed video: %w", err)
	}

	w.logger.Info("Hardsub generation completed",
		zap.String("session_id", p.SessionID),
		zap.String("gcs_uri", hardSubGCSURI))

	return nil
}

// enqueueHardSub is a best-effort helper that enqueues a hardsub generation task.
// Errors are logged but never propagated — hardsub is a nice-to-have, not critical.
func (w *Worker) enqueueHardSub(sessionID string, profileID uint) {
	if profileID == 0 {
		return
	}

	task, err := NewGenerateHardSubTask(sessionID, profileID)
	if err != nil {
		w.logger.Warn("Failed to create hardsub task",
			zap.String("session_id", sessionID),
			zap.Error(err))
		return
	}

	if _, err := w.QueueClient.Enqueue(task); err != nil {
		w.logger.Warn("Failed to enqueue hardsub task",
			zap.String("session_id", sessionID),
			zap.Error(err))
		return
	}

	w.logger.Info("Hardsub generation auto-enqueued after analysis",
		zap.String("session_id", sessionID),
		zap.Uint("profile_id", profileID))
}
